vich_uploader:
    db_driver: orm

    mappings:
        imagen_curso:
            upload_destination: '%kernel.project_dir%/public/assets/images/cursos'
            uri_prefix: /assets/images/cursos
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        imagen_perfil:
            upload_destination: '%kernel.project_dir%/public/assets/images/usuarios'
            uri_prefix: /assets/images/usuarios
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        archivos_plaza:
            upload_destination: '%kernel.project_dir%/public/assets/files/plazas'
            uri_prefix: /assets/files/plazas
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
